### ISSUE TITLE
Can't find parameters in (mobile)Safari

### ISSUE THREAD

**Issue by CharlieAt** [h1pn0z/micropython-wifi_manager#2]
as with tayfunulu's original version there is a problem with setting the password from osx devices
one of the users there supplied a fix which makes it work on these devices too.
https://github.com/tayfunulu/WiFiManager/issues/9#issuecomment-696630527

**Comment by h1pn0z** [comment]
Hi @CharlieAt!

Thanks for the tip! Going to fix in the next update.

**Comment by CharlieAt** [comment]
@h1pn0z 

thanks!
